/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.szu.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.szu.entity.Goods;
import com.szu.entity.GoodsDAO;

/** 
 * MyEclipse Struts
 * Creation date: 05-18-2018
 * 
 * XDoclet definition:
 * @struts.action parameter="opr" validate="true"
 */
public class GoodsAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward select(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GoodsDAO goodsDao = new GoodsDAO();
		List<Goods> goodslist = goodsDao.findAll();
//		request.setAttribute("goodslist", goodslist);
		return mapping.findForward("success");
	}
	
	public ActionForward del(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id = request.getParameter("id");
		
//		System.out.println("ID£º"+id);
		GoodsDAO goodsDao = new GoodsDAO();
		Goods gd =  goodsDao.findById(Integer.valueOf(id));
		
		goodsDao.delete(gd);

		return mapping.findForward("success");
	}
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String id = request.getParameter("id");
		String name = request.getParameter("name");
		String price = request.getParameter("price");
		
		GoodsDAO gd = new GoodsDAO();
		Goods good = gd.findById(Integer.valueOf(id));
		good.setName(name);
		good.setPrice(Double.valueOf(price));
		
		gd.save(good);
		return select(mapping, form, request, response);
	}
	
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		String id = request.getParameter("id");
		String name = request.getParameter("name");
		String price = request.getParameter("price");
		
		GoodsDAO gd = new GoodsDAO();
		Goods good = new Goods(name,Double.valueOf(price));
		
		gd.save(good);
		return select(mapping, form, request, response);
		
		/*if(result > 0){
			return select(mapping, form, request, response);
		}else{
			return mapping.findForward("error");
		}*/
	}
}