/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.szu.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.szu.entity.Users;
import com.szu.entity.UsersDAO;

/** 
 * MyEclipse Struts
 * Creation date: 05-18-2018
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/form/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Users loginForm = (Users) form;// TODO Auto-generated method stub
		UsersDAO userDao = new UsersDAO();
		Users user = new Users(loginForm.getName(),loginForm.getPass());
		List<Users> userlist = userDao.findByExample(user);
		if(userlist.size()>0)
			return mapping.findForward("success");
		else{
			return mapping.findForward("error");
		}
	}
}